FROM confluentinc/cp-zookeeper

ARG JAVA_HOME=/usr/lib/jvm/zulu-8-amd64

RUN apt-get update
RUN apt-get install -y unzip emacs-nox

RUN cd /tmp \
    && wget https://cdn.azul.com/zcek/bin/ZuluJCEPolicies.zip \
    && unzip -jo -d ${JAVA_HOME}/jre/lib/security /tmp/ZuluJCEPolicies.zip \
    && rm /tmp/ZuluJCEPolicies.zip
